### ISSUE TITLE
Jsons quebrados na tradução 'biblia_aa'

### ISSUE THREAD

**Issue by WesleyyRafaell** [wesleycsj/BibliaJSON#2]
Lista de jsons quebrados na tradução 'biblia_aa'.
-Josué
-Juízes
-1 Samuel
-1 Reis
-2 Reis
-Jó
-Salmos
- Provérbios
-Isaías
-Lamentações
-Ezequiel
-Joel
-Atos dos Apóstolos

**Comment by wesleycsj** [comment]
Duplicado de #1
